CoreDemo/CoreDemo/Areas/Admin/Controllers/AdminRoleController.cs
using CoreDemo.Areas.Admin.Models;
using CoreDemo.Models;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreDemo.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin,Moderator")]
public class AdminRoleController : Controller
{
    private readonly RoleManager<AppRole> _roleManager;
    private readonly UserManager<AppUser> _userManager;

    public AdminRoleController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        var data = _roleManager.Roles.ToList();
        return View(data);
    }

    public IActionResult AddRole()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddRole(RoleViewModel model)
    {
        if (ModelState.IsValid)
        {
            AppRole role = new AppRole
            {
                Name = model.Name,
            };
            IdentityResult result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult UpdateRole(int id)
    {
        var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
        RoleUpdateViewModel model = new RoleUpdateViewModel
        {
            Id = values.Id,
            Name = values.Name,
        };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateRole(RoleUpdateViewModel model)
    {
        if (ModelState.IsValid)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == model.Id);
            values.Name = model.Name;
            var result = await _roleManager.UpdateAsync(values);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
        }

        return View(model);
    }

    public async Task<IActionResult> DeleteRole(int id)
    {
        var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
        var result = await _roleManager.DeleteAsync(values);
        if (result.Succeeded)
        {
            return RedirectToAction("Index");
        }
        else
        {
            return View();
        }
    }

    public IActionResult UserRoleList()
    {
        var values = _userManager.Users.ToList();
        return View(values);
    }

    public async Task<IActionResult> AssignRole(int id)
    {
        var user = _userManager.Users.FirstOrDefault(x => x.Id == id);
        var roles = _roleManager.Roles.ToList();

        TempData["UserId"] = user.Id;

        var userRoles = await _userManager.GetRolesAsync(user);

        List<RoleAssignViewModel> model = new List<RoleAssignViewModel>();
        foreach (var role in roles)
        {
            RoleAssignViewModel m = new();
            m.RoleId = role.Id;
            m.Name = role.Name;
            m.Exist = userRoles.Contains(role.Name);
            model.Add(m);
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AssignRole(List<RoleAssignViewModel> model)
    {
        var userId = (int)TempData["UserId"];
        var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == userId);

        foreach (var item in model)
        {
            if (item.Exist)
            {
                await _userManager.AddToRoleAsync(user, item.Name);
            }
            else
            {
                await _userManager.RemoveFromRoleAsync(user, item.Name);
            }
        }

        return RedirectToAction("UserRoleList");
    }
}

CoreDemo/CoreDemo/Areas/Admin/Views/AdminRole/AddRole.cshtml
@using CoreDemo.Models
@model RoleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<h1>Rol Eklem Sayfası</h1>

<form asp-controller="AdminRole" asp-action="AddRole" method="post">
    <div class="row">
        <div class="form-group col-md-4">
            <label for="">Rol Başlığı</label>
            <input asp-for="Name" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            <button class="btn btn-info">Kaydet</button>
        </div>
    </div>

    <div asp-validation-summary="ModelOnly"></div>
</form>

CoreDemo/CoreDemo/Areas/Admin/Views/AdminRole/AssignRole.cshtml
@using CoreDemo.Areas.Admin.Models
@model List<RoleAssignViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<form action="" method="post">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="form-check">
            <input type="hidden" asp-for="@Model[i].RoleId"/>
            <input type="hidden" asp-for="@Model[i].Name"/>
            <input type="checkbox" asp-for="@Model[i].Exist" class="form-check-input">
            <label for="@Model[i].Exist" class="form-check-label">@Model[i].Name</label>
        </div>
    }
    <br>
    <button class="btn btn-info">Değişiklikleri Kaydet</button>
</form>
<br>
<a href="/Admin/AdminRole/UserRoleList/" class="btn btn-primary">Kullanıcı Listesine Dön</a>

CoreDemo/CoreDemo/Areas/Admin/Views/AdminRole/Index.cshtml
@using EntityLayer.Concrete
@model List<AppRole>

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Roller </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#" class="dropdown-item">Config option 1</a>
                            </li>
                            <li><a href="#" class="dropdown-item">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Sil</th>
                            <th>Düzenle</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td><a href="/Admin/AdminRole/DeleteRole/@item.Id" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/Admin/AdminRole/UpdateRole/@item.Id" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                        </tbody>
                    </table>
                    <a href="/Admin/AdminRole/UserRoleList/" class="btn btn-outline-info">Kullanıcı Rol Listesi</a>
                    <a href="/Admin/AdminRole/AddRole/" class="btn btn-outline-primary">Yeni Rol Ekle</a>
                </div>
            </div>
        </div>
    </div>
</div>

CoreDemo/CoreDemo/Areas/Admin/Views/AdminRole/UpdateRole.cshtml
@using CoreDemo.Models
@model RoleUpdateViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<h2>Role Düzenleme Sayfası</h2>

<form asp-controller="AdminRole" asp-action="UpdateRole" method="post">
    <div class="row">
        <div class="form-group col-md-4">
            <label for="">Rol Başlığı</label>
            <input asp-for="Id" class="form-control">
        </div>
    </div>
    
    <div class="row">
        <div class="form-group col-md-4">
            <label for="">Rol Başlığı</label>
            <input asp-for="Name" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            <button class="btn btn-info">Kaydet</button>
        </div>
    </div>

    <div asp-validation-summary="ModelOnly"></div>
</form>

CoreDemo/CoreDemo/Areas/Admin/Views/AdminRole/UserRoleList.cshtml
@using EntityLayer.Concrete
@model List<AppUser>

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<h1>Kullanıcı Rol Listesi</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Kullanıcı</th>
        <th>Rol Ata</th>
    </tr>
    </thead>

    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.UserName</td>
            <td><a href="/Admin/AdminRole/AssignRole/@item.Id/" class="btn btn-outline-warning">Rol Ata</a></td>
        </tr>
    }
    </tbody>

</table>

<a href="/Admin/AdminRole/Index" class="btn btn-primary">Rol Listesine Dön</a>